targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          preamble: // coverage:ignore-file
      # https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
      json_serializable:
        options:
          field_rename: snake
