name: hrk_nasa_apis
version: 0.4.0-dev

description: >-
  A library to integrate NASA Open APIs based on dio HTTP client
repository: https://github.com/hrishikesh-kadam/hrk_nasa_apis.dart
topics:
  - nasa

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  hrk_batteries: '>=0.1.0 <1.0.0'
  hrk_logging: '>=0.1.2 <1.0.0'
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  hrk_analysis: '>=0.1.0 <1.0.0'
  json_serializable: ^6.7.0
  test: ^1.21.0
