name: hrk_nasa_apis
version: 0.16.0

description: >-
  A library to integrate NASA Open APIs based on dio HTTP client
repository: https://github.com/hrishikesh-kadam/hrk_nasa_apis.dart/tree/main/hrk_nasa_apis
topics:
  - nasa

environment:
  sdk: ^3.0.0

dependencies:
  intl: '>=0.18.0 <1.0.0'
  dio: ^5.2.1+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  hrk_batteries: '>=0.8.0 <1.0.0'
  hrk_logging: '>=0.1.3 <1.0.0'

# dependency_overrides:
#   hrk_batteries:
#     path: '../../hrk_batteries'

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.4.5
  hrk_analysis: '>=0.1.0 <1.0.0'
  json_serializable: ^6.7.0
  freezed: ^2.3.5
