name: ci-dev-main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 12:00 PM IST / 6:30 AM GMT every Sunday and Wednesday.
    - cron: '30 6 * * 0,3'

defaults:
  run:
    shell: bash

jobs:
  ci-dev-main:
    name: CI on ${{ matrix.runner }} using Dart ${{ matrix.sdk }}
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        runner: [ ubuntu-latest ]
        sdk: [ dev, main ]
        experimental: [ true ]

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: ./tool/prerequisite.sh
      - run: ./tool/ci.sh
      - uses: codecov/codecov-action@v4
        with:
          files: ./hrk_nasa_apis/coverage/lcov.info
          flags: hrk_nasa_apis
          name: ci-hrk_nasa_apis-${{ matrix.runner }}-${{ matrix.sdk }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/codecov-action@v4
        with:
          files: ./hrk_nasa_apis_test/coverage/lcov.info
          flags: hrk_nasa_apis_test
          name: ci-dev-main-hrk_nasa_apis_test-${{ matrix.runner }}-${{ matrix.sdk }}
          token: ${{ secrets.CODECOV_TOKEN }}
